<%@LANGUAGE="VBSCRIPT" CODEPAGE="65001"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
body {
	background-color: #000;
}
.stylelogin {
	display: table;
	padding: 1px;
	margin-top: 10px;
	margin-right: auto;
	margin-bottom: 10px;
	margin-left: auto;
}
</style>
</head>

<body>




<HR />
<div class="stylelogin">
  
  











<!-- Begin DWUser_EasyRotator -->
  <script type="text/javascript" src="http://c520866.r66.cf2.rackcdn.com/1/js/easy_rotator.min.js"></script>
  <div class="dwuserEasyRotator" style="width: 900px; height: 300px; position:relative; text-align: left; background-color: #CCCCFF;" data-erConfig="{autoplayEnabled:false, lpp:'102-105-108-101-58-47-47-47-67-58-47-85-115-101-114-115-47-103-103-111-110-122-97-108-101-122-47-68-111-99-117-109-101-110-116-115-47-69-97-115-121-82-111-116-97-116-111-114-80-114-101-118-105-101-119-47-112-114-101-118-105-101-119-95-115-119-102-115-47', wv:1}" data-erName="DEMO" data-erTID="{azf74g6anv8939293624631}">
    <div data-ertype="content" style="display: none;"><ul data-erlabel="Main Category">
	<li>
		<img class="main" src="especiales/Especial1_renamed.jpg" />
		<img class="thumb" src="especiales/Especial1_renamed.jpg" />
	</li>
	<li>
		<img class="main" src="especiales/Especial2_renamed.jpg" />
		<img class="thumb" src="especiales/Especial2_renamed.jpg" />
	</li>
	<li>
		<img class="main" src="parts_images/xfs_2000x1500_c80_Especial111.jpg" alt="SDFGSDFG" />
		<img class="thumb" src="parts_images/xfs_thumbs/xfs_700x200_s80_Especial111.jpg" />
		<span class="title">SDFGSDFG</span>
		<span class="desc">DFFFGDSFGDSFGSDFGDSFG</span>
	</li>
	<li>
		<img class="main" src="parts_images/xfs_2000x1500_c80_Especial3.jpg" />
		<img class="thumb" src="parts_images/xfs_thumbs/xfs_700x200_s80_Especial3.jpg" />
		<span class="desc">SDFGSDFGSDFG</span>
	</li>
	<li>
		<img class="main" src="parts_images/xfs_2000x1500_c80_Especial2.jpg" />
		<img class="thumb" src="parts_images/xfs_thumbs/xfs_700x200_s80_Especial2.jpg" />
	</li>
	<li>
		<img class="main" src="parts_images/xfs_2000x1500_c80_Especial111.jpg" />
		<img class="thumb" src="parts_images/xfs_thumbs/xfs_700x200_s80_Especial111.jpg" />
	</li>
</ul>
</div>
    <div data-ertype="layout" data-ertemplateName="NONE" style="">			<div class="erimgMain" style="position: absolute; left:0;right:0;top:0;bottom:0;" data-erConfig="{numTiles:6, scrollSize:3, scaleMode:'fillArea', imgType:'main', treatAsThumbs:true, addMainSlideLinks:false, __loopNextButton:false, __arrowButtonMode:'rollover', alwaysPreviousButton:true}">
				<div class="erimgMain_slides" style="position: absolute; left:10px; top:38px; bottom:10px; right:10px; background:#FFF;">
					<div class="erimgMain_slide" style="color: #666699; border-right:1px solid #CCCCFF;">
						<p class="erimgMain_title" style="position: absolute; left: 10px; right: 10px; top: 10px; bottom: 53px; text-transform:uppercase; color: #FFF; background: #666699; padding: 4px; margin: 0; font-size: 11px; font-family: Arial, _sans;"></p>
						<div class="erimgMain_img" style="position: absolute; left: 10px; right: 10px; top: 30px; bottom: 56px;"></div>
						<p class="erimgMain_desc" style="position: absolute; left: 10px; right: 10px; bottom: 1px; height: 46px; overflow: hidden; text-align: center; padding: 0; margin: 0; font-size: 11px; font-family: Arial, _sans;"></p>
					</div>
				</div>
				<div class="erimgMain_arrowLeft" style="position:absolute; left: 10px; top: 7px;" data-erConfig="{image:'rectSmall', image2:'rectSmall'}"></div>
				<div class="erimgMain_arrowRight" style="position:absolute; left: 50px; top: 7px;" data-erConfig="{image:'rectSmall', image2:'rectSmall'}"></div>
			</div><div class="erabout erFixCSS3" style="color: #FFF; text-align: left; background: #000; background:rgba(0,0,0,0.93); border: 2px solid #FFF; padding: 20px; font: normal 11px/14px Verdana,_sans; width: 300px; border-radius: 10px; display:none;">
          This <a style="color:#FFF;" href="http://www.dwuser.com/easyrotator/" target="_blank">jQuery slider</a> was created with the free <a style="color:#FFF;" href="http://www.dwuser.com/easyrotator/" target="_blank">EasyRotator</a> software from DWUser.com.
          <br /><br />
          Use WordPress? The free <a style="color:#FFF;" href="http://www.dwuser.com/easyrotator/wordpress/" target="_blank">EasyRotator for WordPress</a> plugin lets you create beautiful <a style="color:#FFF;" href="http://www.dwuser.com/easyrotator/wordpress/" target="_blank">WordPress sliders</a> in seconds.
          <br /><br />
          <a style="color:#FFF;" href="#" class="erabout_ok">OK</a>   
          </div>
      <noscript>
        Rotator powered by <a href="http://www.dwuser.com/easyrotator/">EasyRotator</a>, a free and easy jQuery slider builder from DWUser.com.  Please enable JavaScript to view.
        </noscript>
      <script type="text/javascript">/*Avoid IE gzip bug*/(function(b,c,d){try{if(!b[d]){b[d]="temp";var a=c.createElement("script");a.type="text/javascript";a.src="http://easyrotator.s3.amazonaws.com/1/js/nozip/easy_rotator.min.js";c.getElementsByTagName("head")[0].appendChild(a)}}catch(e){alert("EasyRotator fail; contact support.")}})(window,document,"er_$144");</script>
      
      </div>
  </div>
  <!-- End DWUser_EasyRotator -->












</div>
<hr />


</body>
</html>
